### ISSUE TITLE
Question about merging

### ISSUE THREAD

**Issue by Bioinfoq** [bkehr/popins#11]
I merged unaligned contigs from some samples by the command: popins merge. And then,  to group all contigs, I aligned all contigs to merged supercontigs by blastn. But there are about 33% of contigs failed to be aligned to supercontigs. So, I want to ask whether those contigs can be ignored directly or need to be added to the set of supercontigs after merging. Thank you very much!

**Comment by bkehr** [comment]
These are most likely contigs that PopIns failed to merge, see page 4 "Restricting component complexity" in the [Supplementary Text](https://static-content.springer.com/esm/art%3A10.1038%2Fng.3801/MediaObjects/41588_2017_BFng3801_MOESM37_ESM.pdf) of our paper on Icelandic NRNR sequences. Probably, many of these contigs contain repetitive sequences, which is why we decided to ignore them in our analysis.

However, I do not see a problem in appending them to the supercontigs after merging, if you would like to try and place them. Please note that you will need to remove duplicates in case any of these sequences occurs in several individuals.
